Updated es.po and es.man
suve/vrms-rpm pull request #86
Opened 2022-10-15 04:51 UTC by natastro

Hi @suve 

Here is my pull request for #85 
`es.po` and `es.man` have both been updated. If you have any questions or concerns just let me know 😀

Thank you for letting me help with this!

2022-10-15 07:56 UTC, suve requested changes
Thanks! Looks good overall, just a couple minor issues.

2022-10-15 07:56 UTC, suve commented on lang/es.po
> +msgstr "    Además de los nombres de los paquetes, imprima también su epoch:version-release.arch.\n"
Please wrap this to 80 characters per line - that being not 80 characters per line of the `.po` file, but 80 characters per line of the message (so from the opening `"` to the closing `\n"`).

Note: Wrapping is only needed for the `HELP_*` strings. `ERR_*` strings should be left single-line.

2022-10-15 07:56 UTC, suve commented on lang/es.po
> +mgstr "Traducción al Español por Natalie Stroud\n"
1. `mgstr` -> `msgstr` (the first `s` is missing)
2. Please keep the previous translator's name and add your name in an "X and Y" fashion.

2022-10-15 07:56 UTC, suve commented on lang/es.po
> +msgstr "    Al listar paquetes, incluya los resúmenes de paquetes (descripciones breves).\n"
Wrap to 80 characters per line.

2022-10-17 05:56 UTC, natastro commented
Hi @suve - I think I corrected what needed to be changed. If you still see an issue, just let me know! Thank you again!

2022-10-22 18:51 UTC, suve requested changes

2022-10-22 18:51 UTC, suve commented on lang/es.po
> +msgstr "Traducción al Español por Natalie Stroud\n"
This creates two alternative translations for the string. What I'd like you do is something like:
```
msgtr "Traducción al Español por Mr. Outis y Natalie Stroud\n"
```
I don't know Spanish, so no idea if one should use `y` or `e` or something else here.

2022-10-22 18:51 UTC, suve commented on lang/es.po
> + breves).\n"
```
msgstr "    Al listar paquetes, incluya los resúmenes de paquetes (descripciones\n"
       "    breves).\n"
```

2022-10-22 18:51 UTC, suve commented on lang/es.po
> +       "    El valor predeterminado es 'auto', lo que hace esto sólo para los paquetes que comparten un nombre.\n"
```
msgstr "    Además de los nombres de los paquetes, imprima también su\n"
       "    epoch:version-release.arch. El valor predeterminado es 'auto', \n"
       "    lo que hace esto sólo para los paquetes que comparten un nombre.\n"
```

2022-10-23 22:55 UTC, natastro commented
Hi @suve - so sorry about this! These should now be corrected but if you see anything else, feel free to let me know 😀

2022-10-24 17:06 UTC, merged

2022-10-24 17:06 UTC, suve commented
Looks good now. Thanks!